import { Button } from '@welcome-ui/button'
import { RightIcon } from '@welcome-ui/icons'
import Head from 'next/head'
import Link from 'next/link'

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <Button as={Link} href="getting-started" mt="3xl" size="lg">
          <span>Install amazing components</span>
          <RightIcon size="lg" />
        </Button>
      </main>
    </>
  )
}

export default Home
