name: NPM Deploy

on:
  # Defines how to run this workflow manually from the Actions tab
  workflow_dispatch:  
    inputs:
      bump_type:
        type: choice
        description: Release type
        options: 
        - major
        - minor
        - bugfix
        required: true
      release_type:
        type: choice
        description: Release type
        options: 
        - stable
        - alpha
        - dry_run
        required: true
        default: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: whoami
        env: 
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
          npm whoami
